### PR TITLE
add html files for pages

### PR DESCRIPTION
**Pull request by MrJustice**
Add html files for main pages. Login and signup will be made as pop-ups.

### CODE REVIEW

**Comment by gmltA** [comment]
Please, provide deployment link.

**Comment by MrJustice** [comment]
> 
> 
> Please, provide deployment link.

I thought that for the second MS its not necessery.
Should i do it in github pages?

**Comment by gmltA** [comment]
> I thought that for the second MS its not necessery.

That's true. But as I stated in instruction email, I expect you to upload page structure as image with HTML tags over elements.

**Comment by MrJustice** [comment]
> 
> 
> > I thought that for the second MS its not necessery.
> 
> That's true. But as I stated in instruction email, I expect you to upload page structure as image with HTML tags over elements.

It seems we have a little misunderstanding, because page layouts are already in my repository. The fact is that I created the repository on the command line and the first commit was made immediately with the templates in it(actually, my fault). So I couldn’t request them, but they are in repository.

**Comment by MrJustice** [comment]
> 
> 
> > I thought that for the second MS its not necessery.
> 
> That's true. But as I stated in instruction email, I expect you to upload page structure as image with HTML tags over elements.

So, what should i do next? If layouts are already uploaded to my repo.

**Comment by gmltA** [comment]
As stated in the task, I expect page structure image with HTML tags over it.
Or a set of deployed HTML pages in remote server so I can see them in my browser.

**Comment by MrJustice** [comment]
> 
> 
> As stated in the task, I expect page structure image with HTML tags over it.
> Or a set of deployed HTML pages in remote server so I can see them in my browser.

I don’t quite understand how exactly this should look. Something like this?
Desktop - Home (1)

**Comment by gmltA** [comment]
Exactly, but more detailed.

**Comment by MrJustice** [comment]
> 
> 
> Exactly, but more detailed.

Is it ok, if i wrote them(i mean tags) as emmet snippets, so the layout looks a little clearer to understand. And I also think that I will make forms for login and registration as pop-ups.

Desktop - Add tea
Desktop - Home
Desktop - Log in
Desktop - Sign up
Desktop - Single tea
Desktop - Tea Gallery

**Pull request merged**
